name: publish-5_0

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-5_0:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Read .NET version - revision
        uses: bfren/read-file@v1
        with:
          file: ./5.0/DOTNET_REVISION
        id: dotnet_revision
      -
        name: Read image version
        uses: bfren/read-file@v1
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./5.0/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            bfren/aspnet:net5
            bfren/aspnet:net5-${{ steps.version.outputs.contents }}
            bfren/aspnet:net5.0
            bfren/aspnet:net5.0-${{ steps.version.outputs.contents }}
            bfren/aspnet:net${{ steps.dotnet_revision.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
